### ISSUE TITLE
Add setting for double optin

### ISSUE THREAD

**Issue by rclations** [restrictcontentpro/RCP-MailChimp#17]
It would be great to add a setting that controlled whether users receive an opt-in email from Mailchimp before they're subscribed to a list.

**Comment by nosegraze** [comment]
I talked about this with the rest of the team and we realized that this feature is actually available in the MailChimp Pro add-on. We're hesitant to add too much overlap between the two.

How about if instead of adding this feature directly, we add a filter to the MailChimp API request, which would allow you to add the option yourself in another add-on plugin. Would that work for you? :)

**Comment by rclations** [comment]
Where can I find the MailChimp Pro add-on? I wasn't aware that one existed, but I could potentially just use that?

**Comment by nosegraze** [comment]
It's a third party add-on, available here: https://section214.com/product/rcp-mailchimp-pro/

**Comment by rclations** [comment]
Oh! I hadn't even thought to look in 3rd party add-ons. Yeah, a filter would work just fine for my purposes.

**Comment by nosegraze** [comment]
Great! I'm going to create a new issue for that and we'll get it added.
